### ISSUE TITLE
File Upload - multipart/form-data

### ISSUE THREAD

**Issue by fiftycy** [skthomasjr/NetClient.Rest#7]
Can i upload a file from byte[] form using a multipart/form-data post request? i want to replicate this request. 

$ curl https://someaddress.com/ 
-F parameter1='abc123' \
-F file=@myfile.someextension \
-F parameter2='abc123'

**Comment by skthomasjr** [comment]
Not currently. It is still in early prototype stage, but this project is currently my primary focus and new features should be coming online daily.
